stages:
  data_ingestion:
    cmd: python src/deepFakeDetection/pipeline/stage_01_data_ingestion.py
    deps:
      - src/deepFakeDetection/pipeline/stage_01_data_ingestion.py
      - config/config.yaml
      - data/for-norm.tar.gz
    outs:
      - artifacts/data_ingestion/for-norm

  data_transformation:
    cmd: python src/deepFakeDetection/pipeline/stage_02_data_transformation.py
    deps:
      - src/deepFakeDetection/pipeline/stage_02_data_transformation.py
      - config/config.yaml
    outs:
      - artifacts/data_transformation/for-norm

  training:
    cmd: python src/deepFakeDetection/pipeline/stage_03_model_training.py
    deps:
      - src/deepFakeDetection/pipeline/stage_03_model_training.py
      - config/config.yaml
      - artifacts/data_transformation/for-norm
    params:
      - IMAGE_SIZE
      - EPOCHS
      - BATCH_SIZE
      - LEARNING_RATE
      - CLASSES
    outs:
      - artifacts/training/model.h5

  evaluation:
    cmd: python src/deepFakeDetection/pipeline/stage_04_model_evaluation.py
    deps:
      - src/deepFakeDetection/pipeline/stage_04_model_evaluation.py
      - config/config.yaml
      - artifacts/data_transformation/for-norm
      - artifacts/training/model.h5
    params:
      - IMAGE_SIZE
      - EPOCHS
      - BATCH_SIZE
      - LEARNING_RATE
      - CLASSES
    metrics:
    - scores.json:
        cache: false